# Generated by Django 4.1.7 on 2023-03-15 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0003_subcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='main_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.maincat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorys',
            name='sub_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.subcat'),
            preserve_default=False,
        ),
    ]
