# Generated by Django 4.1.7 on 2023-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_maincat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincat',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
