# Generated by Django 4.1.7 on 2023-03-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_categorys_slug_subcat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='slug',
            field=models.SlugField(default=' ', unique=True),
            preserve_default=False,
        ),
    ]
