# Generated by Django 4.1.7 on 2023-03-21 18:20

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_pruduct_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hex_color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='pruduct',
            name='color4',
        ),
        migrations.AddField(
            model_name='pruduct',
            name='colors',
            field=models.ManyToManyField(blank=True, to='shopkeeper.color'),
        ),
    ]
