# Generated by Django 4.1.7 on 2023-03-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_color_remove_pruduct_color_remove_pruduct_color2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
