# Generated by Django 4.1.7 on 2023-04-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0013_alter_pruduct_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruduct',
            name='slug',
            field=models.SlugField(),
        ),
    ]
