# Generated by Django 4.1.7 on 2023-04-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruduct',
            name='riviews',
            field=models.ManyToManyField(blank=True, related_name='riviews', to='shopkeeper.review'),
        ),
    ]
