# Generated by Django 4.1.7 on 2023-04-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0016_pruduct_riviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
