# Generated by Django 4.1.7 on 2023-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0008_pruduct_slug'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saveds', to='shopkeeper.pruduct'),
        ),
    ]
