# Generated by Django 4.1.7 on 2023-03-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdedrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='shopkeeper.pruduct')),
            ],
        ),
        migrations.CreateModel(
            name='Ordedr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('oreder_date', models.DateTimeField(auto_now_add=True)),
                ('has_seen', models.BooleanField(default=False)),
                ('complet', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='order_products', to='basket.ordedritem')),
            ],
        ),
    ]
