# Generated by Django 4.1.7 on 2023-03-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_ordedroption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordedr',
            name='phone',
        ),
        migrations.AddField(
            model_name='ordedr',
            name='ordedrOption',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='OrdedrOption', to='basket.ordedroption'),
            preserve_default=False,
        ),
    ]
