# Generated by Django 4.1.7 on 2023-03-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_ordedr_phone_ordedr_ordedroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordedroption',
            name='price',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=5),
            preserve_default=False,
        ),
    ]
