# Generated by Django 4.1.7 on 2023-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_ordedroption_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordedr',
            name='address',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordedr',
            name='city',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordedr',
            name='contry',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordedr',
            name='postal',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
