# Generated by Django 4.1.7 on 2023-04-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_ordedr_address_ordedr_city_ordedr_contry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordedr',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
